# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46bb5d2dbb1a5ea2a791408bf16aed6a9d8ff916cbd4e468221b4d5c816acaa6393ce6af8c0a982393b289e750a20cc3a891e18ce5d43a6f454f0abc9fd25b23

test:
  secret_key_base: 15a21c8d43871d352818599667e3c9c2c83d74e255bcfa59e548050cfbdc9039fa6bb373364202b6296634b81a2344bc2c29e33594e07a8562d2ecdca59156fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
